<a href="https://colab.research.google.com/github/KeshavFTW099/R_Programming/blob/main/Inference_InR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Data Manipulation and Analysis Using R & Infering**

# Create a student dataset containing Name, Department, Gender, Attendance, and Marks. Using dplyr, display only the students' names, departments, and marks. Then filter students whose marks are greater than 75. Write an inference.

In [30]:
students <- read.csv("/content/student_99.csv")

In [31]:
library(dplyr)

students %>%
  select(Name, Department, Marks)

students %>%
  filter(Marks > 75)

   Name   Department Marks
1  Rahul  CSE        85
2  Priya  AI&DS      91
3  Arjun  ECE        72
4  Sneha  CSE        89
5  Karan  AI&DS      78
6  Ananya EEE        94
7  Vikram CSE        65
8  Riya   ECE        82
9  Aditya AI&DS      74
10 Meera  CSE        88
11 Rohan  EEE        69
12 Ishita AI&DS      97
13 Varun  ECE        76
14 Neha   CSE        81
15 Manav  AI&DS      71
16 Kavya  EEE        86
17 Nitin  CSE        79
18 Pooja  ECE        92
19 Harsh  AI&DS      67
20 Aarav  CSE        83

   Name   Department Gender Attendance Marks
1  Rahul  CSE        Male   92         85
2  Priya  AI&DS      Female 88         91
3  Sneha  CSE        Female 95         89
4  Karan  AI&DS      Male   81         78
5  Ananya EEE        Female 90         94
6  Riya   ECE        Female 87         82
7  Meera  CSE        Female 93         88
8  Ishita AI&DS      Female 96         97
9  Varun  ECE        Male   84         76
10 Neha   CSE        Female 91         81
11 Kavya  EEE        Female 89         86
12 Nitin  CSE        Male   80         79
13 Pooja  ECE        Female 94         92
14 Aarav  CSE        Male   85         83

**Inference:**
-select() function displays only the required student details: Name, Department and Marks.
-filter() function identifies students who scored more than 75 marks.
it becomes easier to focus on selected columns

# Create an employee dataset containing Employee_ID, Department, Salary, and Experience. Arrange the employees in descending order of salary and display the top 5 employees. Provide an inference.

In [32]:
employees <- read.csv("/content/employee_99.csv")

In [33]:
library(dplyr)


employees %>%
  arrange(desc(Salary)) %>%
  head(5)

  Employee_ID Department Salary Experience
1 E117        CSE        98000  10
2 E112        AI&DS      95000   9
3 E107        CSE        92000   8
4 E109        AI&DS      88000   7
5 E104        CSE        85000   6

**Inference**

The employees are arranged from the highest salary to the lowest salary.
The first five records represent the employees with the highest salaries.
This makes it easy to identify the top-paid employees in the organization.

# Create a student dataset with Name, Marks, and Attendance. Using dplyr, create a new column called Result that contains "Pass" if marks ≥ 40 and "Fail" otherwise. Provide an inference about the results.

In [34]:
library(dplyr)

students <- read.csv("/content/student_99.csv")

students %>%
  mutate(Result = ifelse(Marks >= 40, "Pass", "Fail"))

   Name   Department Gender Attendance Marks Result
1  Rahul  CSE        Male   92         85    Pass
2  Priya  AI&DS      Female 88         91    Pass
3  Arjun  ECE        Male   76         72    Pass
4  Sneha  CSE        Female 95         89    Pass
5  Karan  AI&DS      Male   81         78    Pass
6  Ananya EEE        Female 90         94    Pass
7  Vikram CSE        Male   68         65    Pass
8  Riya   ECE        Female 87         82    Pass
9  Aditya AI&DS      Male   79         74    Pass
10 Meera  CSE        Female 93         88    Pass
11 Rohan  EEE        Male   72         69    Pass
12 Ishita AI&DS      Female 96         97    Pass
13 Varun  ECE        Male   84         76    Pass
14 Neha   CSE        Female 91         81    Pass
15 Manav  AI&DS      Male   75         71    Pass
16 Kavya  EEE        Female 89         86    Pass
17 Nitin  CSE        Male   80         79    Pass
18 Pooja  ECE        Female 94         92    Pass
19 Harsh  AI&DS      Male   70         67    Pass
20 Aarav  CSE        Male   85         83    Pass

**Inference**

The mutate() function creates a new column called Result.
Students scoring 40 or above are classified as Pass, while those below 40 are classified as Fail.

# Create a student dataset containing Department and Marks. Using group_by() and summarise(), calculate the average, maximum, and minimum marks for each department. Provide an inference comparing the departments

In [35]:
library(dplyr)

students <- read.csv("/content/student_99.csv")

students %>%
  group_by(Department) %>%
  summarise(
    Average_Marks = mean(Marks),
    Maximum_Marks = max(Marks),
    Minimum_Marks = min(Marks)
  )

  Department Average_Marks Maximum_Marks Minimum_Marks
1 AI&DS      79.66667      97            67
2 CSE        81.42857      89            65
3 ECE        80.50000      92            72
4 EEE        83.00000      94            69

In [36]:
library(dplyr)

students <- read.csv("/content/student_99.csv")

students %>%
  group_by(Department) %>%
  summarise(
    Average_Marks = mean(Marks),
    Maximum_Marks = max(Marks),
    Minimum_Marks = min(Marks)
  )

  Department Average_Marks Maximum_Marks Minimum_Marks
1 AI&DS      79.66667      97            67
2 CSE        81.42857      89            65
3 ECE        80.50000      92            72
4 EEE        83.00000      94            69

**Inference**

AI&DS has the highest average marks among the departments.
CSE follows with a relatively high average
EEE has the lowest average.

# Create an employee dataset containing Department, Gender, and Salary. Using data.table, calculate the average salary for each department and identify the department with the highest average salary. Provide an inference.

In [37]:
library(data.table)
employees<- as.data.table(read.csv("/content/dept_Salary.csv"))

employees[, .(Average_Salary = mean(Salary)), by = Department]

  Department Average_Salary
1 CSE        70000
2 AI&DS      86250
3 ECE        63750
4 EEE        58750

In [38]:
avg_salary <- employees[, .(Average_Salary = mean(Salary)),
                        by = Department]

avg_salary[which.max(Average_Salary)]

  Department Average_Salary
1 AI&DS      86250

**Inference**

The average salary is calculated separately for each department using data.table.
The department with the highest average salary is identified using which.max().
AIDS HAS MAX

# Create a dataset containing students and their marks in Mathematics, Science, English, and Computer Science in wide format. Use pivot_longer() to convert it into long format. Display the resulting dataset and provide an inference about the change in data structure.

In [39]:
library(tidyr)

students <- read.csv("/content/marks_subjects.csv")

students_long <- students %>%
  pivot_longer(
    cols = Mathematics:Computer_Science,
    names_to = "Subject",
    values_to = "Marks"
  )

students_long

   Name   Subject          Marks
1  Rahul  Mathematics      85
2  Rahul  Science          78
3  Rahul  English          82
4  Rahul  Computer_Science 90
5  Priya  Mathematics      92
6  Priya  Science          88
7  Priya  English          95
8  Priya  Computer_Science 94
9  Arjun  Mathematics      74
10 Arjun  Science          70
11 Arjun  English          76
12 Arjun  Computer_Science 80
13 Sneha  Mathematics      89
14 Sneha  Science          91
15 Sneha  English          87
16 Sneha  Computer_Science 93
17 Karan  Mathematics      65
18 Karan  Science          72
19 Karan  English          68
20 Karan  Computer_Science 75
21 Ananya Mathematics      96
22 Ananya Science          94
23 Ananya English          92
24 Ananya Computer_Science 98
25 Vikram Mathematics      58
26 Vikram Science          64
27 Vikram English          61
28 Vikram Computer_Science 70
29 Riya   Mathematics      81
30 Riya   Science          85
31 Riya   English          88
32 Riya   Computer_Science 86
33 Aditya Mathematics      77
34 Aditya Science          73
35 Aditya English          79
36 Aditya Computer_Science 82
37 Meera  Mathematics      90
38 Meera  Science          89
39 Meera  English          94
40 Meera  Computer_Science 96

**Inference**

The original dataset stores each subject as a separate column, which is called wide format.
pivot_longer() converts these subject columns into a single Subject column and their values into a Marks column.

# Create a long-format dataset containing Student, Subject, and Marks. Use pivot_wider() to convert it into wide format where each subject becomes a separate column. Explain the difference between the two formats.

In [40]:
library(tidyr)

students <- read.csv("/content/LONG_Std.csv")

students_wide <- students %>%
  pivot_wider(
    names_from = Subject,
    values_from = Marks
  )

students_wide

  Student Mathematics Science English Computer_Science
1 Rahul   85          78      82      90
2 Priya   92          88      95      94
3 Arjun   74          70      76      80
4 Sneha   89          91      87      93
5 Karan   65          72      68      75

**Inference**

pivot_wider() changes the dataset from long format to wide format.
The subjects that were stored as values in the Subject column become separate columns.
Wide format makes it easier to compare

# Create a dataset containing monthly sales of three products. Use reshape2 to convert the data from wide format to long format using melt(), and then convert it back using dcast(). Explain the purpose of reshaping.

In [43]:
install.packages("reshape2")
library(reshape2)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘plyr’



Attaching package: ‘reshape2’


The following object is masked from ‘package:tidyr’:

    smiths


The following objects are masked from ‘package:data.table’:

    dcast, melt

In [44]:
library(reshape2)

sales <- read.csv("/content/monthlysales99.csv")

sales

  Month    Laptop Mobile Tablet
1 January  45000  38000  25000
2 February 48000  42000  27000
3 March    52000  45000  30000
4 April    50000  47000  32000
5 May      56000  51000  35000
6 June     60000  55000  38000

In [45]:
sales_long <- melt(
  sales,
  id.vars = "Month",
  variable.name = "Product",
  value.name = "Sales"
)

sales_long

   Month    Product Sales
1  January  Laptop  45000
2  February Laptop  48000
3  March    Laptop  52000
4  April    Laptop  50000
5  May      Laptop  56000
6  June     Laptop  60000
7  January  Mobile  38000
8  February Mobile  42000
9  March    Mobile  45000
10 April    Mobile  47000
11 May      Mobile  51000
12 June     Mobile  55000
13 January  Tablet  25000
14 February Tablet  27000
15 March    Tablet  30000
16 April    Tablet  32000
17 May      Tablet  35000
18 June     Tablet  38000

In [46]:
sales_wide <- dcast(
  sales_long,
  Month ~ Product,
  value.var = "Sales"
)

sales_wide

  Month    Laptop Mobile Tablet
1 April    50000  47000  32000
2 February 48000  42000  27000
3 January  45000  38000  25000
4 June     60000  55000  38000
5 March    52000  45000  30000
6 May      56000  51000  35000

**Inference**

melt() converts the sales data from wide format into long format by combining the product columns.
dcast() converts the long data back into its original wide structure.