<a href="https://colab.research.google.com/github/KeshavFTW099/R_Programming/blob/main/Inference_InR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Manipulation and Analysis Using R & Infering

In [1]:
students <- read.csv("/content/student_99.csv")

In [2]:
library(dplyr)

students %>%
  select(Name, Department, Marks)

students %>%
  filter(Marks > 75)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

   Name   Department Marks
1  Rahul  CSE        85
2  Priya  AI&DS      91
3  Arjun  ECE        72
4  Sneha  CSE        89
5  Karan  AI&DS      78
6  Ananya EEE        94
7  Vikram CSE        65
8  Riya   ECE        82
9  Aditya AI&DS      74
10 Meera  CSE        88
11 Rohan  EEE        69
12 Ishita AI&DS      97
13 Varun  ECE        76
14 Neha   CSE        81
15 Manav  AI&DS      71
16 Kavya  EEE        86
17 Nitin  CSE        79
18 Pooja  ECE        92
19 Harsh  AI&DS      67
20 Aarav  CSE        83

   Name   Department Gender Attendance Marks
1  Rahul  CSE        Male   92         85
2  Priya  AI&DS      Female 88         91
3  Sneha  CSE        Female 95         89
4  Karan  AI&DS      Male   81         78
5  Ananya EEE        Female 90         94
6  Riya   ECE        Female 87         82
7  Meera  CSE        Female 93         88
8  Ishita AI&DS      Female 96         97
9  Varun  ECE        Male   84         76
10 Neha   CSE        Female 91         81
11 Kavya  EEE        Female 89         86
12 Nitin  CSE        Male   80         79
13 Pooja  ECE        Female 94         92
14 Aarav  CSE        Male   85         83

**Inference:**
-select() function displays only the required student details: Name, Department and Marks.
-filter() function identifies students who scored more than 75 marks.
it becomes easier to focus on selected columns

In [5]:
employees <- read.csv("/content/employee_99.csv")

In [8]:
library(dplyr)


employees %>%
  arrange(desc(Salary)) %>%
  head(5)

  Employee_ID Department Salary Experience
1 E117        CSE        98000  10
2 E112        AI&DS      95000   9
3 E107        CSE        92000   8
4 E109        AI&DS      88000   7
5 E104        CSE        85000   6

**Inference**

The employees are arranged from the highest salary to the lowest salary.
The first five records represent the employees with the highest salaries.
This makes it easy to identify the top-paid employees in the organization.

In [9]:
library(dplyr)

students <- read.csv("/content/student_99.csv")

students %>%
  mutate(Result = ifelse(Marks >= 40, "Pass", "Fail"))

   Name   Department Gender Attendance Marks Result
1  Rahul  CSE        Male   92         85    Pass
2  Priya  AI&DS      Female 88         91    Pass
3  Arjun  ECE        Male   76         72    Pass
4  Sneha  CSE        Female 95         89    Pass
5  Karan  AI&DS      Male   81         78    Pass
6  Ananya EEE        Female 90         94    Pass
7  Vikram CSE        Male   68         65    Pass
8  Riya   ECE        Female 87         82    Pass
9  Aditya AI&DS      Male   79         74    Pass
10 Meera  CSE        Female 93         88    Pass
11 Rohan  EEE        Male   72         69    Pass
12 Ishita AI&DS      Female 96         97    Pass
13 Varun  ECE        Male   84         76    Pass
14 Neha   CSE        Female 91         81    Pass
15 Manav  AI&DS      Male   75         71    Pass
16 Kavya  EEE        Female 89         86    Pass
17 Nitin  CSE        Male   80         79    Pass
18 Pooja  ECE        Female 94         92    Pass
19 Harsh  AI&DS      Male   70         67    Pass
20 Aarav  CSE        Male   85         83    Pass

**Inference**

The mutate() function creates a new column called Result.
Students scoring 40 or above are classified as Pass, while those below 40 are classified as Fail.

In [11]:
library(dplyr)

students <- read.csv("/content/student_99.csv")

students %>%
  group_by(Department) %>%
  summarise(
    Average_Marks = mean(Marks),
    Maximum_Marks = max(Marks),
    Minimum_Marks = min(Marks)
  )

  Department Average_Marks Maximum_Marks Minimum_Marks
1 AI&DS      79.66667      97            67
2 CSE        81.42857      89            65
3 ECE        80.50000      92            72
4 EEE        83.00000      94            69

In [13]:
library(dplyr)

students <- read.csv("/content/student_99.csv")

students %>%
  group_by(Department) %>%
  summarise(
    Average_Marks = mean(Marks),
    Maximum_Marks = max(Marks),
    Minimum_Marks = min(Marks)
  )

  Department Average_Marks Maximum_Marks Minimum_Marks
1 AI&DS      79.66667      97            67
2 CSE        81.42857      89            65
3 ECE        80.50000      92            72
4 EEE        83.00000      94            69

**Inference**

AI&DS has the highest average marks among the departments.
CSE follows with a relatively high average
EEE has the lowest average.

In [15]:
library(data.table)
employees<- as.data.table(read.csv("/content/dept_Salary.csv"))

employees[, .(Average_Salary = mean(Salary)), by = Department]

  Department Average_Salary
1 CSE        70000
2 AI&DS      86250
3 ECE        63750
4 EEE        58750

In [16]:
avg_salary <- employees[, .(Average_Salary = mean(Salary)),
                        by = Department]

avg_salary[which.max(Average_Salary)]

  Department Average_Salary
1 AI&DS      86250

**Inference**

The average salary is calculated separately for each department using data.table.
The department with the highest average salary is identified using which.max().
AIDS HAS MAX

In [17]:
library(tidyr)

students <- read.csv("/content/marks_subjects.csv")

students_long <- students %>%
  pivot_longer(
    cols = Mathematics:Computer_Science,
    names_to = "Subject",
    values_to = "Marks"
  )

students_long

   Name   Subject          Marks
1  Rahul  Mathematics      85
2  Rahul  Science          78
3  Rahul  English          82
4  Rahul  Computer_Science 90
5  Priya  Mathematics      92
6  Priya  Science          88
7  Priya  English          95
8  Priya  Computer_Science 94
9  Arjun  Mathematics      74
10 Arjun  Science          70
11 Arjun  English          76
12 Arjun  Computer_Science 80
13 Sneha  Mathematics      89
14 Sneha  Science          91
15 Sneha  English          87
16 Sneha  Computer_Science 93
17 Karan  Mathematics      65
18 Karan  Science          72
19 Karan  English          68
20 Karan  Computer_Science 75
21 Ananya Mathematics      96
22 Ananya Science          94
23 Ananya English          92
24 Ananya Computer_Science 98
25 Vikram Mathematics      58
26 Vikram Science          64
27 Vikram English          61
28 Vikram Computer_Science 70
29 Riya   Mathematics      81
30 Riya   Science          85
31 Riya   English          88
32 Riya   Computer_Science 86
33 Aditya Mathematics      77
34 Aditya Science          73
35 Aditya English          79
36 Aditya Computer_Science 82
37 Meera  Mathematics      90
38 Meera  Science          89
39 Meera  English          94
40 Meera  Computer_Science 96

**Inference**

The original dataset stores each subject as a separate column, which is called wide format.
pivot_longer() converts these subject columns into a single Subject column and their values into a Marks column.