<a href="https://colab.research.google.com/github/KeshavFTW099/R_Programming/blob/main/Modelling_Linear_Log_InR_CARS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LINEAR REGRESSION**

In [5]:

car_data <- read.csv("/content/car_regression_classification_dataset_160.csv")

head(car_data)
str(car_data)
summary(car_data)

#Preprocessing
car_data$Brand <- as.factor(car_data$Brand)
car_data$Fuel_Type <- as.factor(car_data$Fuel_Type)

#missing values
colSums(is.na(car_data))

#data into training and testing sets
set.seed(123)

train_index <- sample(
  1:nrow(car_data),
  size = 0.8 * nrow(car_data)
)

train_data <- car_data[train_index, ]
test_data <- car_data[-train_index, ]

#Linear Regression model
linear_model <- lm(
  Price_Lakh ~ Engine_CC + Mileage_kmpl +
    Car_Age + Brand + Fuel_Type,
  data = train_data
)

#Model
summary(linear_model)


predicted_price <- predict(
  linear_model,
  newdata = test_data
)

#RMSE
rmse <- sqrt(
  mean(
    (test_data$Price_Lakh - predicted_price)^2
  )
)

#R-squared
r2 <- cor(
  test_data$Price_Lakh,
  predicted_price
)^2

print(paste("RMSE =", round(rmse, 2)))
print(paste("R² =", round(r2, 2)))

results <- data.frame(
  Actual = test_data$Price_Lakh,
  Predicted = round(predicted_price, 2)
)

head(results, 10)

#Price of a new car
new_car <- data.frame(
  Engine_CC = 1500,
  Mileage_kmpl = 20,
  Car_Age = 3,
  Brand = factor(
    "Hyundai",
    levels = levels(car_data$Brand)
  ),
  Fuel_Type = factor(
    "Petrol",
    levels = levels(car_data$Fuel_Type)
  )
)

new_price <- predict(
  linear_model,
  newdata = new_car
)

print(paste(
  "Predicted Price (Lakhs) =",
  round(new_price, 2)
))

  Car_ID Brand   Fuel_Type Engine_CC Mileage_kmpl Car_Age Price_Lakh
1 1      Skoda   Electric    50      20.1         6       10.75
2 2      Toyota  Petrol    1469      21.2         8       14.12
3 3      Skoda   Diesel    1250      25.2         8        9.82
4 4      Hyundai Petrol     800      26.9         7        8.76
5 5      Hyundai Petrol    1699      22.9         5       12.74
6 6      Kia     Petrol    1282      19.9         7        9.27
  Car_Category
1 Regular
2 Premium
3 Premium
4 Regular
5 Premium
6 Regular

'data.frame':	160 obs. of  8 variables:
 $ Car_ID      : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Brand       : chr  "Skoda" "Toyota" "Skoda" "Hyundai" ...
 $ Fuel_Type   : chr  "Electric" "Petrol" "Diesel" "Petrol" ...
 $ Engine_CC   : int  50 1469 1250 800 1699 1282 944 1457 47 43 ...
 $ Mileage_kmpl: num  20.1 21.2 25.2 26.9 22.9 19.9 22.1 20.9 23.7 12.2 ...
 $ Car_Age     : int  6 8 8 7 5 7 10 8 7 9 ...
 $ Price_Lakh  : num  10.75 14.12 9.82 8.76 12.74 ...
 $ Car_Category: chr  "Regular" "Premium" "Premium" "Regular" ...

     Car_ID             Brand         Fuel_Type     Engine_CC
 Min.   :  1.00   Length   :160   Length   :160   Min.   :   6
 1st Qu.: 40.75   N.unique :  8   N.unique :  4   1st Qu.: 800
 Median : 80.50   N.blank  :  0   N.blank  :  0   Median :1246
 Mean   : 80.50   Min.nchar:  3   Min.nchar:  3   Mean   :1123
 3rd Qu.:120.25   Max.nchar:  8   Max.nchar:  8   3rd Qu.:1494
 Max.   :160.00                                   Max.   :2406
  Mileage_kmpl      Car_Age         Price_Lakh        Car_Category
 Min.   :11.60   Min.   : 1.000   Min.   : 2.500   Length   :160
 1st Qu.:18.90   1st Qu.: 3.000   1st Qu.: 9.143   N.unique :  2
 Median :20.75   Median : 5.000   Median :11.150   N.blank  :  0
 Mean   :20.87   Mean   : 5.338   Mean   :11.164   Min.nchar:  7
 3rd Qu.:23.23   3rd Qu.: 8.000   3rd Qu.:13.488   Max.nchar:  7
 Max.   :27.30   Max.   :10.000   Max.   :20.400

      Car_ID        Brand    Fuel_Type    Engine_CC Mileage_kmpl      Car_Age
           0            0            0            0            0            0
  Price_Lakh Car_Category
           0            0

Call:
lm(formula = Price_Lakh ~ Engine_CC + Mileage_kmpl + Car_Age +
    Brand + Fuel_Type, data = train_data)

Residuals:
    Min      1Q  Median      3Q     Max
-4.0005 -1.1065 -0.0344  1.2497  4.7847

Coefficients:
                    Estimate Std. Error t value Pr(>|t|)
(Intercept)        4.9980451  2.1846876   2.288 0.023996 *
Engine_CC          0.0037405  0.0005983   6.252 7.25e-09 ***
Mileage_kmpl       0.1615675  0.0655207   2.466 0.015156 *
Car_Age           -0.6276196  0.0616728 -10.177  < 2e-16 ***
BrandHyundai      -0.4377831  0.6374802  -0.687 0.493641
BrandKia          -0.1890508  0.7658921  -0.247 0.805478
BrandMahindra      0.4710951  0.6841496   0.689 0.492483
BrandMaruti       -2.1604892  0.6322882  -3.417 0.000879 ***
BrandSkoda         0.8808434  0.6754878   1.304 0.194857
BrandTata         -0.7993317  0.6705999  -1.192 0.235750
BrandToyota        1.2809663  0.6907206   1.855 0.066247 .
Fuel_TypeDiesel    2.0295186  0.7782573   2.608 0.010333 *
Fuel_TypeElectric  4.5639551  1.1977532   3.810 0.000225 ***
Fuel_TypePetrol    1.5821969  0.7075427   2.236 0.027286 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 1.831 on 114 degrees of freedom
Multiple R-squared:  0.6293,	Adjusted R-squared:  0.587
F-statistic: 14.88 on 13 and 114 DF,  p-value: < 2.2e-16

[1] "RMSE = 1.72"
[1] "R² = 0.72"

   Actual Predicted
2  14.12  11.76
3   9.82  11.63
10  7.40   5.25
18  9.88   9.17
20 10.50  10.39
28  9.62  10.21
33  8.89  10.35
48  9.26   9.81
49  9.75   9.87
55 15.29  14.41

[1] "Predicted Price (Lakhs) = 13.1"


**Inference**

The Linear Regression model predicts the price of a car as a continuous numerical value.
RMSE represents the difference between actual and predicted prices, while R² indicates how well the model explains the variation in car prices.
The trained model can also be used to estimate the price of a new car based on its engine, mileage, age, brand and fuel type.

In [6]:
#LOGISTIC REGRESSION
car_data <- read.csv("/content/car_regression_classification_dataset_160.csv")

head(car_data)
str(car_data)
summary(car_data)

# Preprocessing
car_data$Brand <- as.factor(car_data$Brand)
car_data$Fuel_Type <- as.factor(car_data$Fuel_Type)
car_data$Car_Category <- as.factor(car_data$Car_Category)

# missing values
colSums(is.na(car_data))

#data into training and testing sets
set.seed(123)

train_index <- sample(
  1:nrow(car_data),
  size = 0.8 * nrow(car_data)
)

train_data <- car_data[train_index, ]
test_data <- car_data[-train_index, ]

#Logistic Regression model
logistic_model <- glm(
  Car_Category ~ Engine_CC + Mileage_kmpl +
    Car_Age + Brand + Fuel_Type,
  data = train_data,
  family = binomial
)

#model SUMMARY
summary(logistic_model)

#probabilities
probability <- predict(
  logistic_model,
  newdata = test_data,
  type = "response"
)

#probabilities into classes
predicted_class <- ifelse(
  probability >= 0.5,
  "Premium",
  "Regular"
)

predicted_class <- factor(
  predicted_class,
  levels = levels(car_data$Car_Category)
)

# Confusion Matrix
confusion_matrix <- table(
  Actual = test_data$Car_Category,
  Predicted = predicted_class
)

print(confusion_matrix)

# Accuracy
accuracy <- mean(
  predicted_class == test_data$Car_Category
)

#Precision
TP <- confusion_matrix["Premium", "Premium"]
FP <- confusion_matrix["Regular", "Premium"]

precision <- TP / (TP + FP)

#Recall
FN <- confusion_matrix["Premium", "Regular"]

recall <- TP / (TP + FN)

print(paste(
  "Accuracy =", round(accuracy, 2)
))

print(paste(
  "Precision =", round(precision, 2)
))

print(paste(
  "Recall =", round(recall, 2)
))

#actual and predicted classes
results <- data.frame(
  Actual = test_data$Car_Category,
  Predicted = predicted_class
)

head(results, 10)

#category of a new car
new_car <- data.frame(
  Engine_CC = 1500,
  Mileage_kmpl = 20,
  Car_Age = 3,
  Brand = factor(
    "Hyundai",
    levels = levels(car_data$Brand)
  ),
  Fuel_Type = factor(
    "Petrol",
    levels = levels(car_data$Fuel_Type)
  )
)

new_probability <- predict(
  logistic_model,
  newdata = new_car,
  type = "response"
)

new_category <- ifelse(
  new_probability >= 0.5,
  "Premium",
  "Regular"
)

print(paste(
  "Predicted Category =",
  new_category
))

  Car_ID Brand   Fuel_Type Engine_CC Mileage_kmpl Car_Age Price_Lakh
1 1      Skoda   Electric    50      20.1         6       10.75
2 2      Toyota  Petrol    1469      21.2         8       14.12
3 3      Skoda   Diesel    1250      25.2         8        9.82
4 4      Hyundai Petrol     800      26.9         7        8.76
5 5      Hyundai Petrol    1699      22.9         5       12.74
6 6      Kia     Petrol    1282      19.9         7        9.27
  Car_Category
1 Regular
2 Premium
3 Premium
4 Regular
5 Premium
6 Regular

'data.frame':	160 obs. of  8 variables:
 $ Car_ID      : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Brand       : chr  "Skoda" "Toyota" "Skoda" "Hyundai" ...
 $ Fuel_Type   : chr  "Electric" "Petrol" "Diesel" "Petrol" ...
 $ Engine_CC   : int  50 1469 1250 800 1699 1282 944 1457 47 43 ...
 $ Mileage_kmpl: num  20.1 21.2 25.2 26.9 22.9 19.9 22.1 20.9 23.7 12.2 ...
 $ Car_Age     : int  6 8 8 7 5 7 10 8 7 9 ...
 $ Price_Lakh  : num  10.75 14.12 9.82 8.76 12.74 ...
 $ Car_Category: chr  "Regular" "Premium" "Premium" "Regular" ...

     Car_ID             Brand         Fuel_Type     Engine_CC
 Min.   :  1.00   Length   :160   Length   :160   Min.   :   6
 1st Qu.: 40.75   N.unique :  8   N.unique :  4   1st Qu.: 800
 Median : 80.50   N.blank  :  0   N.blank  :  0   Median :1246
 Mean   : 80.50   Min.nchar:  3   Min.nchar:  3   Mean   :1123
 3rd Qu.:120.25   Max.nchar:  8   Max.nchar:  8   3rd Qu.:1494
 Max.   :160.00                                   Max.   :2406
  Mileage_kmpl      Car_Age         Price_Lakh        Car_Category
 Min.   :11.60   Min.   : 1.000   Min.   : 2.500   Length   :160
 1st Qu.:18.90   1st Qu.: 3.000   1st Qu.: 9.143   N.unique :  2
 Median :20.75   Median : 5.000   Median :11.150   N.blank  :  0
 Mean   :20.87   Mean   : 5.338   Mean   :11.164   Min.nchar:  7
 3rd Qu.:23.23   3rd Qu.: 8.000   3rd Qu.:13.488   Max.nchar:  7
 Max.   :27.30   Max.   :10.000   Max.   :20.400

      Car_ID        Brand    Fuel_Type    Engine_CC Mileage_kmpl      Car_Age
           0            0            0            0            0            0
  Price_Lakh Car_Category
           0            0

Call:
glm(formula = Car_Category ~ Engine_CC + Mileage_kmpl + Car_Age +
    Brand + Fuel_Type, family = binomial, data = train_data)

Coefficients:
                   Estimate Std. Error z value Pr(>|z|)
(Intercept)        6.913980   4.159607   1.662  0.09648 .
Engine_CC         -0.004318   0.001334  -3.238  0.00121 **
Mileage_kmpl      -0.240707   0.129778  -1.855  0.06363 .
Car_Age            0.719072   0.152084   4.728 2.27e-06 ***
BrandHyundai       0.763922   1.076771   0.709  0.47804
BrandKia           0.355686   1.253574   0.284  0.77661
BrandMahindra     -1.321126   1.299947  -1.016  0.30949
BrandMaruti        2.846124   1.149228   2.477  0.01327 *
BrandSkoda        -3.186874   1.360500  -2.342  0.01916 *
BrandTata          1.517160   1.097975   1.382  0.16704
BrandToyota       -3.114522   1.611139  -1.933  0.05322 .
Fuel_TypeDiesel   -1.934874   1.257731  -1.538  0.12395
Fuel_TypeElectric -4.544173   2.219962  -2.047  0.04066 *
Fuel_TypePetrol   -2.023220   1.103514  -1.833  0.06674 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 162.008  on 127  degrees of freedom
Residual deviance:  82.665  on 114  degrees of freedom
AIC: 110.66

Number of Fisher Scoring iterations: 6

         Predicted
Actual    Premium Regular
  Premium       2      18
  Regular       8       4
[1] "Accuracy = 0.19"
[1] "Precision = 0.2"
[1] "Recall = 0.1"

   Actual  Predicted
2  Premium Regular
3  Premium Regular
10 Regular Premium
18 Regular Premium
20 Premium Regular
28 Regular Regular
33 Regular Regular
48 Regular Premium
49 Premium Premium
55 Premium Regular

[1] "Predicted Category = Regular"

**Inference**

The Logistic Regression model classifies cars into Premium and Regular categories using their characteristics.
Accuracy, precision, recall and the confusion matrix are used to evaluate the classification performance on the test data.
The model can also classify a new car by calculating its probability and assigning it to the appropriate category.